language: bash

sudo: false

os:
  - linux

env:
  - TEST_DIR=tilt-client
  - TEST_DIR=tilt-server

#before_script:
#  - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script: 
#  - cd $TEST_DIR && npm install && npm test
  - echo $TEST_DIR
