language: bash

#sudo: true   # no virtualenv for these tests
sudo: required
dist: trusty  # 14.04 (16.04 available too?)

os:
  - linux

env:
  global:
    - PYTHONIOENCODING=UTF-8  # bugfix: UnicodeEncodeError
  matrix:
    - TEST_CMD="invoke test_this --yes"
    - TEST_CMD="invoke install_file_metadata_spm --yes install_pywikibot --yes test_script --yes"  # trusty only
    - TEST_CMD="invoke install_file_metadata_pip --yes install_pywikibot --yes test_script --yes"  # trusty only, needs openjdk-7-jre
    - TEST_CMD="invoke install_file_metadata_git --yes install_pywikibot --yes test_script --yes --git"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-7-jre

install:
  - sudo pip install invoke

script: 
  - $TEST_CMD
